
############# OUTPUT NAMES ###########
BINARY = bin/out.elf
DCT_SRC=src/dct.c
DCT_BINARY = bin/dct.elf
BINARY_FINAL = bin/out.bin
BINARY_STRIPPED = bin/out.stripped.elf
DCT_BINARY_FINAL = bin/dct.bin
DCT_BINARY_STRIPPED = bin/dct.stripped.elf

############# DIR NAMES ######
BUILDDIR=build
SOURCEDIR=src
BSP=./bsp

############# RECOURSE FILES ######
HTMLS=resources/index.html 
PNGS=resources/test.png


include ../Makefile.common
