TOOLS_DIR := $(ROOT_DIR)/../tools/
ARG := $(word 2, $(MAKECMDGOALS))
ifeq ($(ARG),)
	ARG=jlink
endif

ifeq ($(ARG), jlink)
	TOOL=$(TOOLS_DIR)/jlink.cfg
download: download_command_1
endif

ifeq ($(ARG), buspirate)
	TOOL=$(TOOLS_DIR)/buspirate.cfg
download: download_command_1
endif

ifeq ($(ARG), busblaster)
	TOOL=$(TOOLS_DIR)/busblaster.cfg
download: download_command_1
endif

ifeq ($(ARG), stlink)
	TOOL=$(TOOLS_DIR)/stlinkv2.cfg
download: download_command_1
endif

ifeq ($(ARG), jlink)
	TOOL=$(TOOLS_DIR)/jlink.cfg
download: download_command_1
endif


######### flash utils ##############
download_command_1: $(BINARY_FINAL)
	sudo openocd -f $(TOOL)  -c "init" -c "halt" -c "flash write_image erase ./bin/bootloader.stripped.elf"  -c shutdown
	sleep 1
	sudo openocd -f $(TOOL) -c "init" -c "halt" -c "flash write_image erase ./bin/dct.stripped.elf" -c shutdown
	sleep 1
	sudo openocd -f $(TOOL) -c "init" -c "halt" -c "flash write_image erase ./bin/out.stripped.elf" -c shutdown


